project_id = "bsndismiessofvhglzrv"

[functions.order-processing]
verify_jwt = false

[functions.order-confirmation]
verify_jwt = false

[functions.admin-notify]
verify_jwt = false

[functions.update-price]
verify_jwt = false

[functions.storage-manager]
verify_jwt = false

[functions.media-manager]
verify_jwt = false

[functions.group-products-by-categories]
verify_jwt = false
