
[build]
  command = "npm run build"
  publish = "dist"

# Serve static assets with proper MIME types
[[headers]]
  for = "/*.js"
  [headers.values]
    Content-Type = "application/javascript"

[[headers]]
  for = "/*.css"
  [headers.values]
    Content-Type = "text/css"

[[headers]]
  for = "/*.html"
  [headers.values]
    Content-Type = "text/html"

[[headers]]
  for = "/images/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

# Handle specific static file routes first (before SPA fallback)
[[redirects]]
  from = "/components/*"
  to = "/components/:splat"
  status = 200

[[redirects]]
  from = "/js/*"
  to = "/js/:splat"
  status = 200

[[redirects]]
  from = "/src/*"
  to = "/src/:splat"
  status = 200

[[redirects]]
  from = "/node_modules/*"
  to = "/node_modules/:splat"
  status = 200

# Supabase Edge Functions (avoid SPA redirect)
[[redirects]]
  from = "/functions/*"
  to = "https://your-project.supabase.co/functions/v1/:splat"
  status = 200

# SPA routing fallback (only for non-static files)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  conditions = {Role = ["admin", "editor"], Country = ["US"]}
